passenger_version: '1:5.1.1-1~`lsb_release -sc`1'
passenger_ruby: "#{ruby_path}/bin/ruby"
passenger_listen_port: 7000
passenger_listen_ssl_port: 7001
max_app_connections: 20

role_dependencies:
  passenger: [apache]

roles:
  passenger:
    packages: [libapache2-mod-xsendfile, libapache2-mod-passenger]
    os_packages:
      '14.04': [apache2-mpm-prefork]
    rolling_restart_port: "#{passenger_listen_port}"

  web_tools:
    rolling_restart_port: "#{web_tools_port}"
