torquebox_version: 2.3.0
torquebox_prefix: /opt
torquebox_dir: "#{torquebox_prefix}/torquebox"
torquebox_log_dir: /var/log/torquebox
torquebox_pid_file: "#{torquebox_dir}/jboss/standalone/torquebox.pid"
torquebox_http_port: 9090
torquebox_https_port: 9443
torquebox_ajp_port: 8009

backstage_user: admin
backstage_password: admin123

mod_cluster_version: 1.3.6

apache_listen_port: 80
apache_listen_ssl_port: 443

roles:
  torquebox:
    packages: [libaio1, unzip, maven, apache2-dev]
    os_packages:
      '14.04': [openjdk-7-jdk]
      '16.04': [openjdk-8-jdk]
    gems: [[torquebox, "#{torquebox_version}"]]
